import kotlinx.serialization.Serializable
import java.math.BigDecimal

@Serializable
data class WeatherInfo(
    val app_temp: Double,
    val aqi: Int,
    val city_name: String,
    val clouds: Int,
    val country_code: String,
    val datetime: String,
    val dewpt: Double,
    val dhi: Int,
    val dni: Int,
    val elev_angle: Double,
    val ghi: Int,
    val gust: Double,
    val h_angle: Double,
    @Serializable(with = BigDecimalSerializer::class)
    val lat: BigDecimal,
    @Serializable(with = BigDecimalSerializer::class)
    val lon: BigDecimal,
    val ob_time: String,
    val pod: String,
    val precip: Int,
    val pres: Double,
    val rh: Int,
    val slp: Int,
    val snow: Int,
    val solar_rad: Int,
    val sources: List<String>,
    val state_code: String,
    val station: String,
    val sunrise: String,
    val sunset: String,
    val temp: Double,
    val timezone: String,
    val ts: Long,
    val uv: Int,
    val vis: Int,
    val weather: Weather,
    val wind_cdir: String,
    val wind_cdir_full: String,
    val wind_dir: Int,
    val wind_spd: Double,
)
